/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppWhatsappRouteImport } from './routes/app.whatsapp'
import { Route as AppTransacoesRouteImport } from './routes/app.transacoes'
import { Route as AppSuporteRouteImport } from './routes/app.suporte'
import { Route as AppSalarioRouteImport } from './routes/app.salario'
import { Route as AppResumoRouteImport } from './routes/app.resumo'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppParceladosRouteImport } from './routes/app.parcelados'
import { Route as AppOrcamentoRouteImport } from './routes/app.orcamento'
import { Route as AppMetasRouteImport } from './routes/app.metas'
import { Route as AppLiberdadeRouteImport } from './routes/app.liberdade'
import { Route as AppLancarRouteImport } from './routes/app.lancar'
import { Route as AppImportarRouteImport } from './routes/app.importar'
import { Route as AppHabitosRouteImport } from './routes/app.habitos'
import { Route as AppDividasRouteImport } from './routes/app.dividas'
import { Route as AppDebugPerfilRouteImport } from './routes/app.debug-perfil'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppContasFixasRouteImport } from './routes/app.contas-fixas'
import { Route as AppCompromissosRouteImport } from './routes/app.compromissos'
import { Route as AppCasalDashboardRouteImport } from './routes/app.casal-dashboard'
import { Route as AppCasalRouteImport } from './routes/app.casal'
import { Route as AppCalendarioRouteImport } from './routes/app.calendario'
import { Route as AppAuditoriaRouteImport } from './routes/app.auditoria'
import { Route as AppAfiliadosRouteImport } from './routes/app.afiliados'
import { Route as AdminWhatsappRouteImport } from './routes/admin.whatsapp'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSistemaRouteImport } from './routes/admin.sistema'
import { Route as AdminPendingMessagesRouteImport } from './routes/admin.pending-messages'
import { Route as AdminOnboardingRouteImport } from './routes/admin.onboarding'
import { Route as AdminMetricasRouteImport } from './routes/admin.metricas'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminIaRouteImport } from './routes/admin.ia'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminDuplicatesRouteImport } from './routes/admin.duplicates'
import { Route as AdminDiagnosticoRouteImport } from './routes/admin.diagnostico'
import { Route as AdminDebugUsersRouteImport } from './routes/admin.debug-users'
import { Route as AdminAuthDebugRouteImport } from './routes/admin.auth-debug'
import { Route as AdminAfiliadosRouteImport } from './routes/admin.afiliados'
import { Route as ApiPublicZapiSetupRouteImport } from './routes/api/public/zapi-setup'
import { Route as ApiPublicWhatsappRouteImport } from './routes/api/public/whatsapp'
import { Route as ApiPublicRRouteImport } from './routes/api/public/r'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as ApiPublicHooksWeeklySummaryRouteImport } from './routes/api/public/hooks/weekly-summary'
import { Route as ApiPublicHooksWaReprocessRouteImport } from './routes/api/public/hooks/wa-reprocess'
import { Route as ApiPublicHooksWaProcessRouteImport } from './routes/api/public/hooks/wa-process'
import { Route as ApiPublicHooksWaBroadcastProcessRouteImport } from './routes/api/public/hooks/wa-broadcast-process'
import { Route as ApiPublicHooksReengagementRouteImport } from './routes/api/public/hooks/reengagement'
import { Route as ApiPublicHooksInstallmentRemindersRouteImport } from './routes/api/public/hooks/installment-reminders'
import { Route as ApiPublicHooksBillRemindersRouteImport } from './routes/api/public/hooks/bill-reminders'
import { Route as ApiPublicHooksBillPaymentCheckRouteImport } from './routes/api/public/hooks/bill-payment-check'
import { Route as ApiPublicHooksAppointmentRemindersRouteImport } from './routes/api/public/hooks/appointment-reminders'
import { Route as ApiPublicAffiliateTrackRouteImport } from './routes/api/public/affiliate/track'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppTransacoesRoute = AppTransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppSuporteRoute = AppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AppRoute,
} as any)
const AppSalarioRoute = AppSalarioRouteImport.update({
  id: '/salario',
  path: '/salario',
  getParentRoute: () => AppRoute,
} as any)
const AppResumoRoute = AppResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppParceladosRoute = AppParceladosRouteImport.update({
  id: '/parcelados',
  path: '/parcelados',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentoRoute = AppOrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppLiberdadeRoute = AppLiberdadeRouteImport.update({
  id: '/liberdade',
  path: '/liberdade',
  getParentRoute: () => AppRoute,
} as any)
const AppLancarRoute = AppLancarRouteImport.update({
  id: '/lancar',
  path: '/lancar',
  getParentRoute: () => AppRoute,
} as any)
const AppImportarRoute = AppImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AppRoute,
} as any)
const AppHabitosRoute = AppHabitosRouteImport.update({
  id: '/habitos',
  path: '/habitos',
  getParentRoute: () => AppRoute,
} as any)
const AppDividasRoute = AppDividasRouteImport.update({
  id: '/dividas',
  path: '/dividas',
  getParentRoute: () => AppRoute,
} as any)
const AppDebugPerfilRoute = AppDebugPerfilRouteImport.update({
  id: '/debug-perfil',
  path: '/debug-perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContasFixasRoute = AppContasFixasRouteImport.update({
  id: '/contas-fixas',
  path: '/contas-fixas',
  getParentRoute: () => AppRoute,
} as any)
const AppCompromissosRoute = AppCompromissosRouteImport.update({
  id: '/compromissos',
  path: '/compromissos',
  getParentRoute: () => AppRoute,
} as any)
const AppCasalDashboardRoute = AppCasalDashboardRouteImport.update({
  id: '/casal-dashboard',
  path: '/casal-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCasalRoute = AppCasalRouteImport.update({
  id: '/casal',
  path: '/casal',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditoriaRoute = AppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppRoute,
} as any)
const AppAfiliadosRoute = AppAfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => AppRoute,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSistemaRoute = AdminSistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPendingMessagesRoute = AdminPendingMessagesRouteImport.update({
  id: '/pending-messages',
  path: '/pending-messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnboardingRoute = AdminOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMetricasRoute = AdminMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIaRoute = AdminIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDuplicatesRoute = AdminDuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiagnosticoRoute = AdminDiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDebugUsersRoute = AdminDebugUsersRouteImport.update({
  id: '/debug-users',
  path: '/debug-users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthDebugRoute = AdminAuthDebugRouteImport.update({
  id: '/auth-debug',
  path: '/auth-debug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAfiliadosRoute = AdminAfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicZapiSetupRoute = ApiPublicZapiSetupRouteImport.update({
  id: '/api/public/zapi-setup',
  path: '/api/public/zapi-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappRoute = ApiPublicWhatsappRouteImport.update({
  id: '/api/public/whatsapp',
  path: '/api/public/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRRoute = ApiPublicRRouteImport.update({
  id: '/api/public/r',
  path: '/api/public/r',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const ApiPublicHooksWeeklySummaryRoute =
  ApiPublicHooksWeeklySummaryRouteImport.update({
    id: '/api/public/hooks/weekly-summary',
    path: '/api/public/hooks/weekly-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWaReprocessRoute =
  ApiPublicHooksWaReprocessRouteImport.update({
    id: '/api/public/hooks/wa-reprocess',
    path: '/api/public/hooks/wa-reprocess',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWaProcessRoute = ApiPublicHooksWaProcessRouteImport.update({
  id: '/api/public/hooks/wa-process',
  path: '/api/public/hooks/wa-process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWaBroadcastProcessRoute =
  ApiPublicHooksWaBroadcastProcessRouteImport.update({
    id: '/api/public/hooks/wa-broadcast-process',
    path: '/api/public/hooks/wa-broadcast-process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReengagementRoute =
  ApiPublicHooksReengagementRouteImport.update({
    id: '/api/public/hooks/reengagement',
    path: '/api/public/hooks/reengagement',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksInstallmentRemindersRoute =
  ApiPublicHooksInstallmentRemindersRouteImport.update({
    id: '/api/public/hooks/installment-reminders',
    path: '/api/public/hooks/installment-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBillRemindersRoute =
  ApiPublicHooksBillRemindersRouteImport.update({
    id: '/api/public/hooks/bill-reminders',
    path: '/api/public/hooks/bill-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBillPaymentCheckRoute =
  ApiPublicHooksBillPaymentCheckRouteImport.update({
    id: '/api/public/hooks/bill-payment-check',
    path: '/api/public/hooks/bill-payment-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAppointmentRemindersRoute =
  ApiPublicHooksAppointmentRemindersRouteImport.update({
    id: '/api/public/hooks/appointment-reminders',
    path: '/api/public/hooks/appointment-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAffiliateTrackRoute = ApiPublicAffiliateTrackRouteImport.update({
  id: '/api/public/affiliate/track',
  path: '/api/public/affiliate/track',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/afiliados': typeof AdminAfiliadosRoute
  '/admin/auth-debug': typeof AdminAuthDebugRoute
  '/admin/debug-users': typeof AdminDebugUsersRoute
  '/admin/diagnostico': typeof AdminDiagnosticoRoute
  '/admin/duplicates': typeof AdminDuplicatesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/metricas': typeof AdminMetricasRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/pending-messages': typeof AdminPendingMessagesRoute
  '/admin/sistema': typeof AdminSistemaRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/app/afiliados': typeof AppAfiliadosRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/casal': typeof AppCasalRoute
  '/app/casal-dashboard': typeof AppCasalDashboardRoute
  '/app/compromissos': typeof AppCompromissosRoute
  '/app/contas-fixas': typeof AppContasFixasRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/debug-perfil': typeof AppDebugPerfilRoute
  '/app/dividas': typeof AppDividasRoute
  '/app/habitos': typeof AppHabitosRoute
  '/app/importar': typeof AppImportarRoute
  '/app/lancar': typeof AppLancarRoute
  '/app/liberdade': typeof AppLiberdadeRoute
  '/app/metas': typeof AppMetasRoute
  '/app/orcamento': typeof AppOrcamentoRoute
  '/app/parcelados': typeof AppParceladosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/resumo': typeof AppResumoRoute
  '/app/salario': typeof AppSalarioRoute
  '/app/suporte': typeof AppSuporteRoute
  '/app/transacoes': typeof AppTransacoesRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/public/r': typeof ApiPublicRRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
  '/api/public/zapi-setup': typeof ApiPublicZapiSetupRoute
  '/api/public/affiliate/track': typeof ApiPublicAffiliateTrackRoute
  '/api/public/hooks/appointment-reminders': typeof ApiPublicHooksAppointmentRemindersRoute
  '/api/public/hooks/bill-payment-check': typeof ApiPublicHooksBillPaymentCheckRoute
  '/api/public/hooks/bill-reminders': typeof ApiPublicHooksBillRemindersRoute
  '/api/public/hooks/installment-reminders': typeof ApiPublicHooksInstallmentRemindersRoute
  '/api/public/hooks/reengagement': typeof ApiPublicHooksReengagementRoute
  '/api/public/hooks/wa-broadcast-process': typeof ApiPublicHooksWaBroadcastProcessRoute
  '/api/public/hooks/wa-process': typeof ApiPublicHooksWaProcessRoute
  '/api/public/hooks/wa-reprocess': typeof ApiPublicHooksWaReprocessRoute
  '/api/public/hooks/weekly-summary': typeof ApiPublicHooksWeeklySummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/afiliados': typeof AdminAfiliadosRoute
  '/admin/auth-debug': typeof AdminAuthDebugRoute
  '/admin/debug-users': typeof AdminDebugUsersRoute
  '/admin/diagnostico': typeof AdminDiagnosticoRoute
  '/admin/duplicates': typeof AdminDuplicatesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/metricas': typeof AdminMetricasRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/pending-messages': typeof AdminPendingMessagesRoute
  '/admin/sistema': typeof AdminSistemaRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/app/afiliados': typeof AppAfiliadosRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/casal': typeof AppCasalRoute
  '/app/casal-dashboard': typeof AppCasalDashboardRoute
  '/app/compromissos': typeof AppCompromissosRoute
  '/app/contas-fixas': typeof AppContasFixasRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/debug-perfil': typeof AppDebugPerfilRoute
  '/app/dividas': typeof AppDividasRoute
  '/app/habitos': typeof AppHabitosRoute
  '/app/importar': typeof AppImportarRoute
  '/app/lancar': typeof AppLancarRoute
  '/app/liberdade': typeof AppLiberdadeRoute
  '/app/metas': typeof AppMetasRoute
  '/app/orcamento': typeof AppOrcamentoRoute
  '/app/parcelados': typeof AppParceladosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/resumo': typeof AppResumoRoute
  '/app/salario': typeof AppSalarioRoute
  '/app/suporte': typeof AppSuporteRoute
  '/app/transacoes': typeof AppTransacoesRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/public/r': typeof ApiPublicRRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
  '/api/public/zapi-setup': typeof ApiPublicZapiSetupRoute
  '/api/public/affiliate/track': typeof ApiPublicAffiliateTrackRoute
  '/api/public/hooks/appointment-reminders': typeof ApiPublicHooksAppointmentRemindersRoute
  '/api/public/hooks/bill-payment-check': typeof ApiPublicHooksBillPaymentCheckRoute
  '/api/public/hooks/bill-reminders': typeof ApiPublicHooksBillRemindersRoute
  '/api/public/hooks/installment-reminders': typeof ApiPublicHooksInstallmentRemindersRoute
  '/api/public/hooks/reengagement': typeof ApiPublicHooksReengagementRoute
  '/api/public/hooks/wa-broadcast-process': typeof ApiPublicHooksWaBroadcastProcessRoute
  '/api/public/hooks/wa-process': typeof ApiPublicHooksWaProcessRoute
  '/api/public/hooks/wa-reprocess': typeof ApiPublicHooksWaReprocessRoute
  '/api/public/hooks/weekly-summary': typeof ApiPublicHooksWeeklySummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/afiliados': typeof AdminAfiliadosRoute
  '/admin/auth-debug': typeof AdminAuthDebugRoute
  '/admin/debug-users': typeof AdminDebugUsersRoute
  '/admin/diagnostico': typeof AdminDiagnosticoRoute
  '/admin/duplicates': typeof AdminDuplicatesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/metricas': typeof AdminMetricasRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/pending-messages': typeof AdminPendingMessagesRoute
  '/admin/sistema': typeof AdminSistemaRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/app/afiliados': typeof AppAfiliadosRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/casal': typeof AppCasalRoute
  '/app/casal-dashboard': typeof AppCasalDashboardRoute
  '/app/compromissos': typeof AppCompromissosRoute
  '/app/contas-fixas': typeof AppContasFixasRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/debug-perfil': typeof AppDebugPerfilRoute
  '/app/dividas': typeof AppDividasRoute
  '/app/habitos': typeof AppHabitosRoute
  '/app/importar': typeof AppImportarRoute
  '/app/lancar': typeof AppLancarRoute
  '/app/liberdade': typeof AppLiberdadeRoute
  '/app/metas': typeof AppMetasRoute
  '/app/orcamento': typeof AppOrcamentoRoute
  '/app/parcelados': typeof AppParceladosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/resumo': typeof AppResumoRoute
  '/app/salario': typeof AppSalarioRoute
  '/app/suporte': typeof AppSuporteRoute
  '/app/transacoes': typeof AppTransacoesRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/public/r': typeof ApiPublicRRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
  '/api/public/zapi-setup': typeof ApiPublicZapiSetupRoute
  '/api/public/affiliate/track': typeof ApiPublicAffiliateTrackRoute
  '/api/public/hooks/appointment-reminders': typeof ApiPublicHooksAppointmentRemindersRoute
  '/api/public/hooks/bill-payment-check': typeof ApiPublicHooksBillPaymentCheckRoute
  '/api/public/hooks/bill-reminders': typeof ApiPublicHooksBillRemindersRoute
  '/api/public/hooks/installment-reminders': typeof ApiPublicHooksInstallmentRemindersRoute
  '/api/public/hooks/reengagement': typeof ApiPublicHooksReengagementRoute
  '/api/public/hooks/wa-broadcast-process': typeof ApiPublicHooksWaBroadcastProcessRoute
  '/api/public/hooks/wa-process': typeof ApiPublicHooksWaProcessRoute
  '/api/public/hooks/wa-reprocess': typeof ApiPublicHooksWaReprocessRoute
  '/api/public/hooks/weekly-summary': typeof ApiPublicHooksWeeklySummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/admin/afiliados'
    | '/admin/auth-debug'
    | '/admin/debug-users'
    | '/admin/diagnostico'
    | '/admin/duplicates'
    | '/admin/financeiro'
    | '/admin/ia'
    | '/admin/login'
    | '/admin/metricas'
    | '/admin/onboarding'
    | '/admin/pending-messages'
    | '/admin/sistema'
    | '/admin/users'
    | '/admin/whatsapp'
    | '/app/afiliados'
    | '/app/auditoria'
    | '/app/calendario'
    | '/app/casal'
    | '/app/casal-dashboard'
    | '/app/compromissos'
    | '/app/contas-fixas'
    | '/app/dashboard'
    | '/app/debug-perfil'
    | '/app/dividas'
    | '/app/habitos'
    | '/app/importar'
    | '/app/lancar'
    | '/app/liberdade'
    | '/app/metas'
    | '/app/orcamento'
    | '/app/parcelados'
    | '/app/perfil'
    | '/app/relatorios'
    | '/app/resumo'
    | '/app/salario'
    | '/app/suporte'
    | '/app/transacoes'
    | '/app/whatsapp'
    | '/admin/'
    | '/app/'
    | '/admin/users/$userId'
    | '/api/public/r'
    | '/api/public/whatsapp'
    | '/api/public/zapi-setup'
    | '/api/public/affiliate/track'
    | '/api/public/hooks/appointment-reminders'
    | '/api/public/hooks/bill-payment-check'
    | '/api/public/hooks/bill-reminders'
    | '/api/public/hooks/installment-reminders'
    | '/api/public/hooks/reengagement'
    | '/api/public/hooks/wa-broadcast-process'
    | '/api/public/hooks/wa-process'
    | '/api/public/hooks/wa-reprocess'
    | '/api/public/hooks/weekly-summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/admin/afiliados'
    | '/admin/auth-debug'
    | '/admin/debug-users'
    | '/admin/diagnostico'
    | '/admin/duplicates'
    | '/admin/financeiro'
    | '/admin/ia'
    | '/admin/login'
    | '/admin/metricas'
    | '/admin/onboarding'
    | '/admin/pending-messages'
    | '/admin/sistema'
    | '/admin/users'
    | '/admin/whatsapp'
    | '/app/afiliados'
    | '/app/auditoria'
    | '/app/calendario'
    | '/app/casal'
    | '/app/casal-dashboard'
    | '/app/compromissos'
    | '/app/contas-fixas'
    | '/app/dashboard'
    | '/app/debug-perfil'
    | '/app/dividas'
    | '/app/habitos'
    | '/app/importar'
    | '/app/lancar'
    | '/app/liberdade'
    | '/app/metas'
    | '/app/orcamento'
    | '/app/parcelados'
    | '/app/perfil'
    | '/app/relatorios'
    | '/app/resumo'
    | '/app/salario'
    | '/app/suporte'
    | '/app/transacoes'
    | '/app/whatsapp'
    | '/admin'
    | '/app'
    | '/admin/users/$userId'
    | '/api/public/r'
    | '/api/public/whatsapp'
    | '/api/public/zapi-setup'
    | '/api/public/affiliate/track'
    | '/api/public/hooks/appointment-reminders'
    | '/api/public/hooks/bill-payment-check'
    | '/api/public/hooks/bill-reminders'
    | '/api/public/hooks/installment-reminders'
    | '/api/public/hooks/reengagement'
    | '/api/public/hooks/wa-broadcast-process'
    | '/api/public/hooks/wa-process'
    | '/api/public/hooks/wa-reprocess'
    | '/api/public/hooks/weekly-summary'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/admin/afiliados'
    | '/admin/auth-debug'
    | '/admin/debug-users'
    | '/admin/diagnostico'
    | '/admin/duplicates'
    | '/admin/financeiro'
    | '/admin/ia'
    | '/admin/login'
    | '/admin/metricas'
    | '/admin/onboarding'
    | '/admin/pending-messages'
    | '/admin/sistema'
    | '/admin/users'
    | '/admin/whatsapp'
    | '/app/afiliados'
    | '/app/auditoria'
    | '/app/calendario'
    | '/app/casal'
    | '/app/casal-dashboard'
    | '/app/compromissos'
    | '/app/contas-fixas'
    | '/app/dashboard'
    | '/app/debug-perfil'
    | '/app/dividas'
    | '/app/habitos'
    | '/app/importar'
    | '/app/lancar'
    | '/app/liberdade'
    | '/app/metas'
    | '/app/orcamento'
    | '/app/parcelados'
    | '/app/perfil'
    | '/app/relatorios'
    | '/app/resumo'
    | '/app/salario'
    | '/app/suporte'
    | '/app/transacoes'
    | '/app/whatsapp'
    | '/admin/'
    | '/app/'
    | '/admin/users/$userId'
    | '/api/public/r'
    | '/api/public/whatsapp'
    | '/api/public/zapi-setup'
    | '/api/public/affiliate/track'
    | '/api/public/hooks/appointment-reminders'
    | '/api/public/hooks/bill-payment-check'
    | '/api/public/hooks/bill-reminders'
    | '/api/public/hooks/installment-reminders'
    | '/api/public/hooks/reengagement'
    | '/api/public/hooks/wa-broadcast-process'
    | '/api/public/hooks/wa-process'
    | '/api/public/hooks/wa-reprocess'
    | '/api/public/hooks/weekly-summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicRRoute: typeof ApiPublicRRoute
  ApiPublicWhatsappRoute: typeof ApiPublicWhatsappRoute
  ApiPublicZapiSetupRoute: typeof ApiPublicZapiSetupRoute
  ApiPublicAffiliateTrackRoute: typeof ApiPublicAffiliateTrackRoute
  ApiPublicHooksAppointmentRemindersRoute: typeof ApiPublicHooksAppointmentRemindersRoute
  ApiPublicHooksBillPaymentCheckRoute: typeof ApiPublicHooksBillPaymentCheckRoute
  ApiPublicHooksBillRemindersRoute: typeof ApiPublicHooksBillRemindersRoute
  ApiPublicHooksInstallmentRemindersRoute: typeof ApiPublicHooksInstallmentRemindersRoute
  ApiPublicHooksReengagementRoute: typeof ApiPublicHooksReengagementRoute
  ApiPublicHooksWaBroadcastProcessRoute: typeof ApiPublicHooksWaBroadcastProcessRoute
  ApiPublicHooksWaProcessRoute: typeof ApiPublicHooksWaProcessRoute
  ApiPublicHooksWaReprocessRoute: typeof ApiPublicHooksWaReprocessRoute
  ApiPublicHooksWeeklySummaryRoute: typeof ApiPublicHooksWeeklySummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/whatsapp': {
      id: '/app/whatsapp'
      path: '/whatsapp'
      fullPath: '/app/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transacoes': {
      id: '/app/transacoes'
      path: '/transacoes'
      fullPath: '/app/transacoes'
      preLoaderRoute: typeof AppTransacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suporte': {
      id: '/app/suporte'
      path: '/suporte'
      fullPath: '/app/suporte'
      preLoaderRoute: typeof AppSuporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/salario': {
      id: '/app/salario'
      path: '/salario'
      fullPath: '/app/salario'
      preLoaderRoute: typeof AppSalarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resumo': {
      id: '/app/resumo'
      path: '/resumo'
      fullPath: '/app/resumo'
      preLoaderRoute: typeof AppResumoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parcelados': {
      id: '/app/parcelados'
      path: '/parcelados'
      fullPath: '/app/parcelados'
      preLoaderRoute: typeof AppParceladosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orcamento': {
      id: '/app/orcamento'
      path: '/orcamento'
      fullPath: '/app/orcamento'
      preLoaderRoute: typeof AppOrcamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/metas': {
      id: '/app/metas'
      path: '/metas'
      fullPath: '/app/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/liberdade': {
      id: '/app/liberdade'
      path: '/liberdade'
      fullPath: '/app/liberdade'
      preLoaderRoute: typeof AppLiberdadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lancar': {
      id: '/app/lancar'
      path: '/lancar'
      fullPath: '/app/lancar'
      preLoaderRoute: typeof AppLancarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/importar': {
      id: '/app/importar'
      path: '/importar'
      fullPath: '/app/importar'
      preLoaderRoute: typeof AppImportarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/habitos': {
      id: '/app/habitos'
      path: '/habitos'
      fullPath: '/app/habitos'
      preLoaderRoute: typeof AppHabitosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dividas': {
      id: '/app/dividas'
      path: '/dividas'
      fullPath: '/app/dividas'
      preLoaderRoute: typeof AppDividasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/debug-perfil': {
      id: '/app/debug-perfil'
      path: '/debug-perfil'
      fullPath: '/app/debug-perfil'
      preLoaderRoute: typeof AppDebugPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contas-fixas': {
      id: '/app/contas-fixas'
      path: '/contas-fixas'
      fullPath: '/app/contas-fixas'
      preLoaderRoute: typeof AppContasFixasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compromissos': {
      id: '/app/compromissos'
      path: '/compromissos'
      fullPath: '/app/compromissos'
      preLoaderRoute: typeof AppCompromissosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/casal-dashboard': {
      id: '/app/casal-dashboard'
      path: '/casal-dashboard'
      fullPath: '/app/casal-dashboard'
      preLoaderRoute: typeof AppCasalDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/casal': {
      id: '/app/casal'
      path: '/casal'
      fullPath: '/app/casal'
      preLoaderRoute: typeof AppCasalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendario': {
      id: '/app/calendario'
      path: '/calendario'
      fullPath: '/app/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/auditoria': {
      id: '/app/auditoria'
      path: '/auditoria'
      fullPath: '/app/auditoria'
      preLoaderRoute: typeof AppAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/afiliados': {
      id: '/app/afiliados'
      path: '/afiliados'
      fullPath: '/app/afiliados'
      preLoaderRoute: typeof AppAfiliadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sistema': {
      id: '/admin/sistema'
      path: '/sistema'
      fullPath: '/admin/sistema'
      preLoaderRoute: typeof AdminSistemaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pending-messages': {
      id: '/admin/pending-messages'
      path: '/pending-messages'
      fullPath: '/admin/pending-messages'
      preLoaderRoute: typeof AdminPendingMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/onboarding': {
      id: '/admin/onboarding'
      path: '/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AdminOnboardingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/metricas': {
      id: '/admin/metricas'
      path: '/metricas'
      fullPath: '/admin/metricas'
      preLoaderRoute: typeof AdminMetricasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ia': {
      id: '/admin/ia'
      path: '/ia'
      fullPath: '/admin/ia'
      preLoaderRoute: typeof AdminIaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/duplicates': {
      id: '/admin/duplicates'
      path: '/duplicates'
      fullPath: '/admin/duplicates'
      preLoaderRoute: typeof AdminDuplicatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diagnostico': {
      id: '/admin/diagnostico'
      path: '/diagnostico'
      fullPath: '/admin/diagnostico'
      preLoaderRoute: typeof AdminDiagnosticoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/debug-users': {
      id: '/admin/debug-users'
      path: '/debug-users'
      fullPath: '/admin/debug-users'
      preLoaderRoute: typeof AdminDebugUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auth-debug': {
      id: '/admin/auth-debug'
      path: '/auth-debug'
      fullPath: '/admin/auth-debug'
      preLoaderRoute: typeof AdminAuthDebugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/afiliados': {
      id: '/admin/afiliados'
      path: '/afiliados'
      fullPath: '/admin/afiliados'
      preLoaderRoute: typeof AdminAfiliadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/zapi-setup': {
      id: '/api/public/zapi-setup'
      path: '/api/public/zapi-setup'
      fullPath: '/api/public/zapi-setup'
      preLoaderRoute: typeof ApiPublicZapiSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp': {
      id: '/api/public/whatsapp'
      path: '/api/public/whatsapp'
      fullPath: '/api/public/whatsapp'
      preLoaderRoute: typeof ApiPublicWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/r': {
      id: '/api/public/r'
      path: '/api/public/r'
      fullPath: '/api/public/r'
      preLoaderRoute: typeof ApiPublicRRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/api/public/hooks/weekly-summary': {
      id: '/api/public/hooks/weekly-summary'
      path: '/api/public/hooks/weekly-summary'
      fullPath: '/api/public/hooks/weekly-summary'
      preLoaderRoute: typeof ApiPublicHooksWeeklySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/wa-reprocess': {
      id: '/api/public/hooks/wa-reprocess'
      path: '/api/public/hooks/wa-reprocess'
      fullPath: '/api/public/hooks/wa-reprocess'
      preLoaderRoute: typeof ApiPublicHooksWaReprocessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/wa-process': {
      id: '/api/public/hooks/wa-process'
      path: '/api/public/hooks/wa-process'
      fullPath: '/api/public/hooks/wa-process'
      preLoaderRoute: typeof ApiPublicHooksWaProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/wa-broadcast-process': {
      id: '/api/public/hooks/wa-broadcast-process'
      path: '/api/public/hooks/wa-broadcast-process'
      fullPath: '/api/public/hooks/wa-broadcast-process'
      preLoaderRoute: typeof ApiPublicHooksWaBroadcastProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reengagement': {
      id: '/api/public/hooks/reengagement'
      path: '/api/public/hooks/reengagement'
      fullPath: '/api/public/hooks/reengagement'
      preLoaderRoute: typeof ApiPublicHooksReengagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/installment-reminders': {
      id: '/api/public/hooks/installment-reminders'
      path: '/api/public/hooks/installment-reminders'
      fullPath: '/api/public/hooks/installment-reminders'
      preLoaderRoute: typeof ApiPublicHooksInstallmentRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/bill-reminders': {
      id: '/api/public/hooks/bill-reminders'
      path: '/api/public/hooks/bill-reminders'
      fullPath: '/api/public/hooks/bill-reminders'
      preLoaderRoute: typeof ApiPublicHooksBillRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/bill-payment-check': {
      id: '/api/public/hooks/bill-payment-check'
      path: '/api/public/hooks/bill-payment-check'
      fullPath: '/api/public/hooks/bill-payment-check'
      preLoaderRoute: typeof ApiPublicHooksBillPaymentCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/appointment-reminders': {
      id: '/api/public/hooks/appointment-reminders'
      path: '/api/public/hooks/appointment-reminders'
      fullPath: '/api/public/hooks/appointment-reminders'
      preLoaderRoute: typeof ApiPublicHooksAppointmentRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/affiliate/track': {
      id: '/api/public/affiliate/track'
      path: '/api/public/affiliate/track'
      fullPath: '/api/public/affiliate/track'
      preLoaderRoute: typeof ApiPublicAffiliateTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAfiliadosRoute: typeof AdminAfiliadosRoute
  AdminAuthDebugRoute: typeof AdminAuthDebugRoute
  AdminDebugUsersRoute: typeof AdminDebugUsersRoute
  AdminDiagnosticoRoute: typeof AdminDiagnosticoRoute
  AdminDuplicatesRoute: typeof AdminDuplicatesRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminIaRoute: typeof AdminIaRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMetricasRoute: typeof AdminMetricasRoute
  AdminOnboardingRoute: typeof AdminOnboardingRoute
  AdminPendingMessagesRoute: typeof AdminPendingMessagesRoute
  AdminSistemaRoute: typeof AdminSistemaRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAfiliadosRoute: AdminAfiliadosRoute,
  AdminAuthDebugRoute: AdminAuthDebugRoute,
  AdminDebugUsersRoute: AdminDebugUsersRoute,
  AdminDiagnosticoRoute: AdminDiagnosticoRoute,
  AdminDuplicatesRoute: AdminDuplicatesRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminIaRoute: AdminIaRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMetricasRoute: AdminMetricasRoute,
  AdminOnboardingRoute: AdminOnboardingRoute,
  AdminPendingMessagesRoute: AdminPendingMessagesRoute,
  AdminSistemaRoute: AdminSistemaRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminWhatsappRoute: AdminWhatsappRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAfiliadosRoute: typeof AppAfiliadosRoute
  AppAuditoriaRoute: typeof AppAuditoriaRoute
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppCasalRoute: typeof AppCasalRoute
  AppCasalDashboardRoute: typeof AppCasalDashboardRoute
  AppCompromissosRoute: typeof AppCompromissosRoute
  AppContasFixasRoute: typeof AppContasFixasRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDebugPerfilRoute: typeof AppDebugPerfilRoute
  AppDividasRoute: typeof AppDividasRoute
  AppHabitosRoute: typeof AppHabitosRoute
  AppImportarRoute: typeof AppImportarRoute
  AppLancarRoute: typeof AppLancarRoute
  AppLiberdadeRoute: typeof AppLiberdadeRoute
  AppMetasRoute: typeof AppMetasRoute
  AppOrcamentoRoute: typeof AppOrcamentoRoute
  AppParceladosRoute: typeof AppParceladosRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppResumoRoute: typeof AppResumoRoute
  AppSalarioRoute: typeof AppSalarioRoute
  AppSuporteRoute: typeof AppSuporteRoute
  AppTransacoesRoute: typeof AppTransacoesRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAfiliadosRoute: AppAfiliadosRoute,
  AppAuditoriaRoute: AppAuditoriaRoute,
  AppCalendarioRoute: AppCalendarioRoute,
  AppCasalRoute: AppCasalRoute,
  AppCasalDashboardRoute: AppCasalDashboardRoute,
  AppCompromissosRoute: AppCompromissosRoute,
  AppContasFixasRoute: AppContasFixasRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDebugPerfilRoute: AppDebugPerfilRoute,
  AppDividasRoute: AppDividasRoute,
  AppHabitosRoute: AppHabitosRoute,
  AppImportarRoute: AppImportarRoute,
  AppLancarRoute: AppLancarRoute,
  AppLiberdadeRoute: AppLiberdadeRoute,
  AppMetasRoute: AppMetasRoute,
  AppOrcamentoRoute: AppOrcamentoRoute,
  AppParceladosRoute: AppParceladosRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppResumoRoute: AppResumoRoute,
  AppSalarioRoute: AppSalarioRoute,
  AppSuporteRoute: AppSuporteRoute,
  AppTransacoesRoute: AppTransacoesRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicRRoute: ApiPublicRRoute,
  ApiPublicWhatsappRoute: ApiPublicWhatsappRoute,
  ApiPublicZapiSetupRoute: ApiPublicZapiSetupRoute,
  ApiPublicAffiliateTrackRoute: ApiPublicAffiliateTrackRoute,
  ApiPublicHooksAppointmentRemindersRoute:
    ApiPublicHooksAppointmentRemindersRoute,
  ApiPublicHooksBillPaymentCheckRoute: ApiPublicHooksBillPaymentCheckRoute,
  ApiPublicHooksBillRemindersRoute: ApiPublicHooksBillRemindersRoute,
  ApiPublicHooksInstallmentRemindersRoute:
    ApiPublicHooksInstallmentRemindersRoute,
  ApiPublicHooksReengagementRoute: ApiPublicHooksReengagementRoute,
  ApiPublicHooksWaBroadcastProcessRoute: ApiPublicHooksWaBroadcastProcessRoute,
  ApiPublicHooksWaProcessRoute: ApiPublicHooksWaProcessRoute,
  ApiPublicHooksWaReprocessRoute: ApiPublicHooksWaReprocessRoute,
  ApiPublicHooksWeeklySummaryRoute: ApiPublicHooksWeeklySummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
